[build]
  publish = "outputs"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/sync-excel"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/.netlify/functions/sync-cadastros"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/.netlify/functions/base-online"
  [headers.values]
    Cache-Control = "no-store"
